### ISSUE TITLE
"API Table of Contents" doesn't fully work

### ISSUE THREAD

**Issue by KingsMMA** [the-h-team/Labyrinth#16]
The following options don't work:

- AFK Player Utility
- Command Builder
- Command Utility
- Custom gradient colour interface
- Directional Enumeration
- Economy interface wrapper
- Entity creation tools
- File management
- Item Recipe Builder
- Item Modification Builder
- Legacy Safe NamespacedKey
- Material Matcher
- Message Formatter
- Tab Completion Builder
- Template Creation
- Text Component Builder
- Vault Permission Interface Wrapper

**Comment by KingsMMA** [comment]
In the library section:

- Applicable Data
- Annotation Discovery
- Base64 Serialization
- Cuboid Generation
- List Formatting Utility
- Math Formatting Utility
- Persistent Data Container
- Reflective Class Instantiation
- Region Services w/ Flag Abstraction
(all bar 2 in this section)

**Comment by Hempfest** [comment]
Hi! Sorry for the inconvenience but i just updated that as of today! Im still completing the wiki while updating other stuff but in the mean time if you have a piece of utility youd like to use and need a tutorial on thats not posted yet let me know so i can get it added asap!

**Comment by Hempfest** [comment]
Expect all wiki pages to be partially/fully completed by the end of today.
