### ISSUE TITLE
Javadoc fails due to misplaced @throws

### ISSUE THREAD

**Issue by ms5984** [the-h-team/Labyrinth#25]
![Screenshot from 2021-09-04 22-00-45](https://user-images.githubusercontent.com/58913953/132112440-0b410491-4fd6-4c06-99eb-de14634916d2.png)

**Comment by ms5984** [comment]
@Hempfest that's gonna block the deploy, if possible see if you can use the mvn javadoc target locally to find+fix these before we try to deploy on here

**Comment by Hempfest** [comment]
Just pushed a commit.
