### ISSUE TITLE
Unclear messages 

### ISSUE THREAD

**Issue by Hajatoby** [the-h-team/Labyrinth#27]
hey,
I keep getting these messages.
Always affects the Pocket Edition users who join via the Geyser Proxy.
But I don't know exactly how to fix it.
or is it a bug with the plugin? 
![Screenshot_1](https://user-images.githubusercontent.com/50121920/158545245-8d5c4fad-73ff-4611-aa99-f7406400b131.png)

**Comment by ms5984** [comment]
Hello @Hajatoby , thanks for bringing this to my attention. Labyrinth provides a service for identifying persistent player data, and it is likely that a) there is a plugin querying this data; and b) that our library might need to be modified to work properly with Geyser. I can't prove a time estimate right now, but as long as functionality of the plugin is not adversely affected I would recommend filtering these warnings from your log.

**Comment by Hajatoby** [comment]
Okay thank you very much.
These logs have been occurring since Microsoft, Mojang or whoever changed the player query a few days/weeks ago.
Geyser had the problem that the player authentication suddenly didn't work and had to change it.

**Comment by Hajatoby** [comment]
That was on February 2nd, 2022
There no PE player could be checked anymore.
Here is a link to the Geyser Quick Fix if it helps. 
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/58/

https://github.com/GeyserMC/Floodgate/commit/5e51ac9f487913a0508788748b43fd66d27c6587

**Comment by Hempfest** [comment]
@Hajatoby Contact me on discord privately, Hempfest#8264 id like to work with you for a solution
