### ISSUE TITLE
Add plugin-based Message utility factory

### ISSUE THREAD

**Issue by ms5984** [the-h-team/Labyrinth#5]
Use case:

Current code:
```java
String prefix = "[MyPluginName]";
new Message(prefix).info("My message");
```

Potential code
```java
Message.loggedFor(plugin).info("My message");
```

Can just use the getLogger method found on JavaPlugin which automatically prepends a prefix of the format "[`PluginName`]"

**Comment by Hempfest** [comment]
Added.
